version: '3.8'

services:
  app:
    build:
      context: ./
    ports:
      - "8080:8080"
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.12.0/28
          gateway: 172.42.12.1